server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:accountsdb
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application-qa.yml"
      - "application-prod.yml"
build:
  info: "v1"
accounts:
  message: "Welcome to accounts APIs"
  contactDetails:
    name: "John Doe"
    email: "johndoe@email.com"
    role: "Developer"
  onCallSupport:
    - (111) 12345-1242
    - (222) 12345-1243